// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.770000,HLS_SYN_LAT=1053,HLS_SYN_TPT=1052,HLS_SYN_MEM=4,HLS_SYN_DSP=8,HLS_SYN_FF=5886,HLS_SYN_LUT=9533,HLS_VERSION=2019_2}" *)

module myproject (
        input_1_V_data_0_V_TDATA,
        input_1_V_data_1_V_TDATA,
        input_1_V_data_2_V_TDATA,
        input_1_V_data_3_V_TDATA,
        input_1_V_data_4_V_TDATA,
        input_1_V_data_5_V_TDATA,
        input_1_V_data_6_V_TDATA,
        input_1_V_data_7_V_TDATA,
        layer2_out_V_data_0_V_TDATA,
        layer2_out_V_data_1_V_TDATA,
        layer2_out_V_data_2_V_TDATA,
        layer2_out_V_data_3_V_TDATA,
        layer2_out_V_data_4_V_TDATA,
        layer2_out_V_data_5_V_TDATA,
        layer2_out_V_data_6_V_TDATA,
        layer2_out_V_data_7_V_TDATA,
        ap_clk,
        ap_rst_n,
        input_1_V_data_0_V_TVALID,
        input_1_V_data_0_V_TREADY,
        input_1_V_data_1_V_TVALID,
        input_1_V_data_1_V_TREADY,
        input_1_V_data_2_V_TVALID,
        input_1_V_data_2_V_TREADY,
        input_1_V_data_3_V_TVALID,
        input_1_V_data_3_V_TREADY,
        input_1_V_data_4_V_TVALID,
        input_1_V_data_4_V_TREADY,
        input_1_V_data_5_V_TVALID,
        input_1_V_data_5_V_TREADY,
        input_1_V_data_6_V_TVALID,
        input_1_V_data_6_V_TREADY,
        input_1_V_data_7_V_TVALID,
        input_1_V_data_7_V_TREADY,
        ap_start,
        layer2_out_V_data_0_V_TVALID,
        layer2_out_V_data_0_V_TREADY,
        layer2_out_V_data_1_V_TVALID,
        layer2_out_V_data_1_V_TREADY,
        layer2_out_V_data_2_V_TVALID,
        layer2_out_V_data_2_V_TREADY,
        layer2_out_V_data_3_V_TVALID,
        layer2_out_V_data_3_V_TREADY,
        layer2_out_V_data_4_V_TVALID,
        layer2_out_V_data_4_V_TREADY,
        layer2_out_V_data_5_V_TVALID,
        layer2_out_V_data_5_V_TREADY,
        layer2_out_V_data_6_V_TVALID,
        layer2_out_V_data_6_V_TREADY,
        layer2_out_V_data_7_V_TVALID,
        layer2_out_V_data_7_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] input_1_V_data_0_V_TDATA;
input  [15:0] input_1_V_data_1_V_TDATA;
input  [15:0] input_1_V_data_2_V_TDATA;
input  [15:0] input_1_V_data_3_V_TDATA;
input  [15:0] input_1_V_data_4_V_TDATA;
input  [15:0] input_1_V_data_5_V_TDATA;
input  [15:0] input_1_V_data_6_V_TDATA;
input  [15:0] input_1_V_data_7_V_TDATA;
output  [15:0] layer2_out_V_data_0_V_TDATA;
output  [15:0] layer2_out_V_data_1_V_TDATA;
output  [15:0] layer2_out_V_data_2_V_TDATA;
output  [15:0] layer2_out_V_data_3_V_TDATA;
output  [15:0] layer2_out_V_data_4_V_TDATA;
output  [15:0] layer2_out_V_data_5_V_TDATA;
output  [15:0] layer2_out_V_data_6_V_TDATA;
output  [15:0] layer2_out_V_data_7_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_1_V_data_0_V_TVALID;
output   input_1_V_data_0_V_TREADY;
input   input_1_V_data_1_V_TVALID;
output   input_1_V_data_1_V_TREADY;
input   input_1_V_data_2_V_TVALID;
output   input_1_V_data_2_V_TREADY;
input   input_1_V_data_3_V_TVALID;
output   input_1_V_data_3_V_TREADY;
input   input_1_V_data_4_V_TVALID;
output   input_1_V_data_4_V_TREADY;
input   input_1_V_data_5_V_TVALID;
output   input_1_V_data_5_V_TREADY;
input   input_1_V_data_6_V_TVALID;
output   input_1_V_data_6_V_TREADY;
input   input_1_V_data_7_V_TVALID;
output   input_1_V_data_7_V_TREADY;
input   ap_start;
output   layer2_out_V_data_0_V_TVALID;
input   layer2_out_V_data_0_V_TREADY;
output   layer2_out_V_data_1_V_TVALID;
input   layer2_out_V_data_1_V_TREADY;
output   layer2_out_V_data_2_V_TVALID;
input   layer2_out_V_data_2_V_TREADY;
output   layer2_out_V_data_3_V_TVALID;
input   layer2_out_V_data_3_V_TREADY;
output   layer2_out_V_data_4_V_TVALID;
input   layer2_out_V_data_4_V_TREADY;
output   layer2_out_V_data_5_V_TVALID;
input   layer2_out_V_data_5_V_TREADY;
output   layer2_out_V_data_6_V_TVALID;
input   layer2_out_V_data_6_V_TREADY;
output   layer2_out_V_data_7_V_TVALID;
input   layer2_out_V_data_7_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_start;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_done;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_continue;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_idle;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_ready;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_start_out;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_start_write;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_0_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_1_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_2_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_3_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_4_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_5_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_6_V_TREADY;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_7_V_TREADY;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_write;
wire   [15:0] zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_din;
wire    zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_write;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_start;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_done;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_continue;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_idle;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_ready;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_0_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_1_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_2_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_3_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_4_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_5_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_6_V_read;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_7_V_read;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TVALID;
wire   [15:0] conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TDATA;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TVALID;
wire    ap_sync_continue;
wire    layer4_out_V_data_0_V_full_n;
wire   [15:0] layer4_out_V_data_0_V_dout;
wire    layer4_out_V_data_0_V_empty_n;
wire    layer4_out_V_data_1_V_full_n;
wire   [15:0] layer4_out_V_data_1_V_dout;
wire    layer4_out_V_data_1_V_empty_n;
wire    layer4_out_V_data_2_V_full_n;
wire   [15:0] layer4_out_V_data_2_V_dout;
wire    layer4_out_V_data_2_V_empty_n;
wire    layer4_out_V_data_3_V_full_n;
wire   [15:0] layer4_out_V_data_3_V_dout;
wire    layer4_out_V_data_3_V_empty_n;
wire    layer4_out_V_data_4_V_full_n;
wire   [15:0] layer4_out_V_data_4_V_dout;
wire    layer4_out_V_data_4_V_empty_n;
wire    layer4_out_V_data_5_V_full_n;
wire   [15:0] layer4_out_V_data_5_V_dout;
wire    layer4_out_V_data_5_V_empty_n;
wire    layer4_out_V_data_6_V_full_n;
wire   [15:0] layer4_out_V_data_6_V_dout;
wire    layer4_out_V_data_6_V_empty_n;
wire    layer4_out_V_data_7_V_full_n;
wire   [15:0] layer4_out_V_data_7_V_dout;
wire    layer4_out_V_data_7_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_din;
wire    start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_dout;
wire    start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_empty_n;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_start_full_n;
wire    conv_2d_cl_array_array_ap_fixed_8u_config2_U0_start_write;

zeropad2d_cl_array_array_ap_fixed_8u_config4_s zeropad2d_cl_array_array_ap_fixed_8u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_full_n),
    .ap_done(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_done),
    .ap_continue(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_continue),
    .ap_idle(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_idle),
    .ap_ready(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_ready),
    .start_out(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_start_out),
    .start_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_start_write),
    .data_V_data_0_V_TDATA(input_1_V_data_0_V_TDATA),
    .data_V_data_0_V_TVALID(input_1_V_data_0_V_TVALID),
    .data_V_data_0_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_0_V_TREADY),
    .data_V_data_1_V_TDATA(input_1_V_data_1_V_TDATA),
    .data_V_data_1_V_TVALID(input_1_V_data_1_V_TVALID),
    .data_V_data_1_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_1_V_TREADY),
    .data_V_data_2_V_TDATA(input_1_V_data_2_V_TDATA),
    .data_V_data_2_V_TVALID(input_1_V_data_2_V_TVALID),
    .data_V_data_2_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_2_V_TREADY),
    .data_V_data_3_V_TDATA(input_1_V_data_3_V_TDATA),
    .data_V_data_3_V_TVALID(input_1_V_data_3_V_TVALID),
    .data_V_data_3_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_3_V_TREADY),
    .data_V_data_4_V_TDATA(input_1_V_data_4_V_TDATA),
    .data_V_data_4_V_TVALID(input_1_V_data_4_V_TVALID),
    .data_V_data_4_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_4_V_TREADY),
    .data_V_data_5_V_TDATA(input_1_V_data_5_V_TDATA),
    .data_V_data_5_V_TVALID(input_1_V_data_5_V_TVALID),
    .data_V_data_5_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_5_V_TREADY),
    .data_V_data_6_V_TDATA(input_1_V_data_6_V_TDATA),
    .data_V_data_6_V_TVALID(input_1_V_data_6_V_TVALID),
    .data_V_data_6_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_6_V_TREADY),
    .data_V_data_7_V_TDATA(input_1_V_data_7_V_TDATA),
    .data_V_data_7_V_TVALID(input_1_V_data_7_V_TVALID),
    .data_V_data_7_V_TREADY(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_7_V_TREADY),
    .res_V_data_0_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_din),
    .res_V_data_0_V_full_n(layer4_out_V_data_0_V_full_n),
    .res_V_data_0_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_write),
    .res_V_data_1_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_din),
    .res_V_data_1_V_full_n(layer4_out_V_data_1_V_full_n),
    .res_V_data_1_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_write),
    .res_V_data_2_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_din),
    .res_V_data_2_V_full_n(layer4_out_V_data_2_V_full_n),
    .res_V_data_2_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_write),
    .res_V_data_3_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_din),
    .res_V_data_3_V_full_n(layer4_out_V_data_3_V_full_n),
    .res_V_data_3_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_write),
    .res_V_data_4_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_din),
    .res_V_data_4_V_full_n(layer4_out_V_data_4_V_full_n),
    .res_V_data_4_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_write),
    .res_V_data_5_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_din),
    .res_V_data_5_V_full_n(layer4_out_V_data_5_V_full_n),
    .res_V_data_5_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_write),
    .res_V_data_6_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_din),
    .res_V_data_6_V_full_n(layer4_out_V_data_6_V_full_n),
    .res_V_data_6_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_write),
    .res_V_data_7_V_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_din),
    .res_V_data_7_V_full_n(layer4_out_V_data_7_V_full_n),
    .res_V_data_7_V_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_write)
);

conv_2d_cl_array_array_ap_fixed_8u_config2_s conv_2d_cl_array_array_ap_fixed_8u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_start),
    .ap_done(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_ready),
    .data_V_data_0_V_dout(layer4_out_V_data_0_V_dout),
    .data_V_data_0_V_empty_n(layer4_out_V_data_0_V_empty_n),
    .data_V_data_0_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_0_V_read),
    .data_V_data_1_V_dout(layer4_out_V_data_1_V_dout),
    .data_V_data_1_V_empty_n(layer4_out_V_data_1_V_empty_n),
    .data_V_data_1_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_1_V_read),
    .data_V_data_2_V_dout(layer4_out_V_data_2_V_dout),
    .data_V_data_2_V_empty_n(layer4_out_V_data_2_V_empty_n),
    .data_V_data_2_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_2_V_read),
    .data_V_data_3_V_dout(layer4_out_V_data_3_V_dout),
    .data_V_data_3_V_empty_n(layer4_out_V_data_3_V_empty_n),
    .data_V_data_3_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_3_V_read),
    .data_V_data_4_V_dout(layer4_out_V_data_4_V_dout),
    .data_V_data_4_V_empty_n(layer4_out_V_data_4_V_empty_n),
    .data_V_data_4_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_4_V_read),
    .data_V_data_5_V_dout(layer4_out_V_data_5_V_dout),
    .data_V_data_5_V_empty_n(layer4_out_V_data_5_V_empty_n),
    .data_V_data_5_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_5_V_read),
    .data_V_data_6_V_dout(layer4_out_V_data_6_V_dout),
    .data_V_data_6_V_empty_n(layer4_out_V_data_6_V_empty_n),
    .data_V_data_6_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_6_V_read),
    .data_V_data_7_V_dout(layer4_out_V_data_7_V_dout),
    .data_V_data_7_V_empty_n(layer4_out_V_data_7_V_empty_n),
    .data_V_data_7_V_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_7_V_read),
    .res_V_data_0_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TDATA),
    .res_V_data_0_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TVALID),
    .res_V_data_0_V_TREADY(layer2_out_V_data_0_V_TREADY),
    .res_V_data_1_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TDATA),
    .res_V_data_1_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TVALID),
    .res_V_data_1_V_TREADY(layer2_out_V_data_1_V_TREADY),
    .res_V_data_2_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TDATA),
    .res_V_data_2_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TVALID),
    .res_V_data_2_V_TREADY(layer2_out_V_data_2_V_TREADY),
    .res_V_data_3_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TDATA),
    .res_V_data_3_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TVALID),
    .res_V_data_3_V_TREADY(layer2_out_V_data_3_V_TREADY),
    .res_V_data_4_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TDATA),
    .res_V_data_4_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TVALID),
    .res_V_data_4_V_TREADY(layer2_out_V_data_4_V_TREADY),
    .res_V_data_5_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TDATA),
    .res_V_data_5_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TVALID),
    .res_V_data_5_V_TREADY(layer2_out_V_data_5_V_TREADY),
    .res_V_data_6_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TDATA),
    .res_V_data_6_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TVALID),
    .res_V_data_6_V_TREADY(layer2_out_V_data_6_V_TREADY),
    .res_V_data_7_V_TDATA(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TDATA),
    .res_V_data_7_V_TVALID(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TVALID),
    .res_V_data_7_V_TREADY(layer2_out_V_data_7_V_TREADY)
);

fifo_w16_d25_A layer4_out_V_data_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_din),
    .if_full_n(layer4_out_V_data_0_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_0_V_write),
    .if_dout(layer4_out_V_data_0_V_dout),
    .if_empty_n(layer4_out_V_data_0_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_0_V_read)
);

fifo_w16_d25_A layer4_out_V_data_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_din),
    .if_full_n(layer4_out_V_data_1_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_1_V_write),
    .if_dout(layer4_out_V_data_1_V_dout),
    .if_empty_n(layer4_out_V_data_1_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_1_V_read)
);

fifo_w16_d25_A layer4_out_V_data_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_din),
    .if_full_n(layer4_out_V_data_2_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_2_V_write),
    .if_dout(layer4_out_V_data_2_V_dout),
    .if_empty_n(layer4_out_V_data_2_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_2_V_read)
);

fifo_w16_d25_A layer4_out_V_data_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_din),
    .if_full_n(layer4_out_V_data_3_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_3_V_write),
    .if_dout(layer4_out_V_data_3_V_dout),
    .if_empty_n(layer4_out_V_data_3_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_3_V_read)
);

fifo_w16_d25_A layer4_out_V_data_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_din),
    .if_full_n(layer4_out_V_data_4_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_4_V_write),
    .if_dout(layer4_out_V_data_4_V_dout),
    .if_empty_n(layer4_out_V_data_4_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_4_V_read)
);

fifo_w16_d25_A layer4_out_V_data_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_din),
    .if_full_n(layer4_out_V_data_5_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_5_V_write),
    .if_dout(layer4_out_V_data_5_V_dout),
    .if_empty_n(layer4_out_V_data_5_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_5_V_read)
);

fifo_w16_d25_A layer4_out_V_data_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_din),
    .if_full_n(layer4_out_V_data_6_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_6_V_write),
    .if_dout(layer4_out_V_data_6_V_dout),
    .if_empty_n(layer4_out_V_data_6_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_6_V_read)
);

fifo_w16_d25_A layer4_out_V_data_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_din),
    .if_full_n(layer4_out_V_data_7_V_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_res_V_data_7_V_write),
    .if_dout(layer4_out_V_data_7_V_dout),
    .if_empty_n(layer4_out_V_data_7_V_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_data_V_data_7_V_read)
);

start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0 start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_full_n),
    .if_write(zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_empty_n),
    .if_read(conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_ready)
);

assign ap_done = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_done;

assign ap_idle = (zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_idle & conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_idle);

assign ap_ready = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_done;

assign ap_sync_ready = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_ready;

assign conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_array_ap_fixed_8u_config2_U0_ap_start = start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_empty_n;

assign conv_2d_cl_array_array_ap_fixed_8u_config2_U0_start_full_n = 1'b1;

assign conv_2d_cl_array_array_ap_fixed_8u_config2_U0_start_write = 1'b0;

assign input_1_V_data_0_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_0_V_TREADY;

assign input_1_V_data_1_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_1_V_TREADY;

assign input_1_V_data_2_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_2_V_TREADY;

assign input_1_V_data_3_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_3_V_TREADY;

assign input_1_V_data_4_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_4_V_TREADY;

assign input_1_V_data_5_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_5_V_TREADY;

assign input_1_V_data_6_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_6_V_TREADY;

assign input_1_V_data_7_V_TREADY = zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_data_V_data_7_V_TREADY;

assign layer2_out_V_data_0_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TDATA;

assign layer2_out_V_data_0_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_0_V_TVALID;

assign layer2_out_V_data_1_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TDATA;

assign layer2_out_V_data_1_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_1_V_TVALID;

assign layer2_out_V_data_2_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TDATA;

assign layer2_out_V_data_2_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_2_V_TVALID;

assign layer2_out_V_data_3_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TDATA;

assign layer2_out_V_data_3_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_3_V_TVALID;

assign layer2_out_V_data_4_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TDATA;

assign layer2_out_V_data_4_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_4_V_TVALID;

assign layer2_out_V_data_5_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TDATA;

assign layer2_out_V_data_5_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_5_V_TVALID;

assign layer2_out_V_data_6_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TDATA;

assign layer2_out_V_data_6_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_6_V_TVALID;

assign layer2_out_V_data_7_V_TDATA = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TDATA;

assign layer2_out_V_data_7_V_TVALID = conv_2d_cl_array_array_ap_fixed_8u_config2_U0_res_V_data_7_V_TVALID;

assign start_for_conv_2d_cl_array_array_ap_fixed_8u_config2_U0_din = 1'b1;

assign zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_continue = 1'b1;

assign zeropad2d_cl_array_array_ap_fixed_8u_config4_U0_ap_start = ap_start;

endmodule //myproject
