-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity zeropad2d_cl_array_array_ap_fixed_8u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_0_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_0_V_TVALID : IN STD_LOGIC;
    data_V_data_0_V_TREADY : OUT STD_LOGIC;
    data_V_data_1_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_1_V_TVALID : IN STD_LOGIC;
    data_V_data_1_V_TREADY : OUT STD_LOGIC;
    data_V_data_2_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_2_V_TVALID : IN STD_LOGIC;
    data_V_data_2_V_TREADY : OUT STD_LOGIC;
    data_V_data_3_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_3_V_TVALID : IN STD_LOGIC;
    data_V_data_3_V_TREADY : OUT STD_LOGIC;
    data_V_data_4_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_4_V_TVALID : IN STD_LOGIC;
    data_V_data_4_V_TREADY : OUT STD_LOGIC;
    data_V_data_5_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_5_V_TVALID : IN STD_LOGIC;
    data_V_data_5_V_TREADY : OUT STD_LOGIC;
    data_V_data_6_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_6_V_TVALID : IN STD_LOGIC;
    data_V_data_6_V_TREADY : OUT STD_LOGIC;
    data_V_data_7_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_7_V_TVALID : IN STD_LOGIC;
    data_V_data_7_V_TREADY : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC;
    res_V_data_3_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_3_V_full_n : IN STD_LOGIC;
    res_V_data_3_V_write : OUT STD_LOGIC;
    res_V_data_4_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_4_V_full_n : IN STD_LOGIC;
    res_V_data_4_V_write : OUT STD_LOGIC;
    res_V_data_5_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_5_V_full_n : IN STD_LOGIC;
    res_V_data_5_V_write : OUT STD_LOGIC;
    res_V_data_6_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_6_V_full_n : IN STD_LOGIC;
    res_V_data_6_V_write : OUT STD_LOGIC;
    res_V_data_7_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_7_V_full_n : IN STD_LOGIC;
    res_V_data_7_V_write : OUT STD_LOGIC );
end;


architecture behav of zeropad2d_cl_array_array_ap_fixed_8u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_V_data_0_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln90_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_data_1_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_2_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_3_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_4_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_5_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_6_V_TDATA_blk_n : STD_LOGIC;
    signal data_V_data_7_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln81_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln86_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln99_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_3_V_blk_n : STD_LOGIC;
    signal res_V_data_4_V_blk_n : STD_LOGIC;
    signal res_V_data_5_V_blk_n : STD_LOGIC;
    signal res_V_data_6_V_blk_n : STD_LOGIC;
    signal res_V_data_7_V_blk_n : STD_LOGIC;
    signal j_fu_298_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal io_acc_block_signal_op31 : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal i_fu_310_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_reg_391 : STD_LOGIC_VECTOR (1 downto 0);
    signal io_acc_block_signal_op43 : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal j_2_fu_322_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal io_acc_block_signal_op54 : STD_LOGIC;
    signal io_acc_block_signal_op63 : STD_LOGIC;
    signal io_acc_block_signal_op66 : STD_LOGIC;
    signal ap_block_state4 : BOOLEAN;
    signal j_1_fu_374_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal io_acc_block_signal_op75 : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal j_0_reg_248 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i1_0_reg_259 : STD_LOGIC_VECTOR (1 downto 0);
    signal j3_0_reg_270 : STD_LOGIC_VECTOR (1 downto 0);
    signal j6_0_reg_281 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_data_V_data_0_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_0_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_0_V_TVALID_int : STD_LOGIC;
    signal data_V_data_0_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_0_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_1_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_1_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_1_V_TVALID_int : STD_LOGIC;
    signal data_V_data_1_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_1_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_2_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_2_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_2_V_TVALID_int : STD_LOGIC;
    signal data_V_data_2_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_2_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_3_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_3_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_3_V_TVALID_int : STD_LOGIC;
    signal data_V_data_3_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_3_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_4_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_4_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_4_V_TVALID_int : STD_LOGIC;
    signal data_V_data_4_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_4_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_5_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_5_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_5_V_TVALID_int : STD_LOGIC;
    signal data_V_data_5_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_5_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_6_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_6_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_6_V_TVALID_int : STD_LOGIC;
    signal data_V_data_6_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_6_V_U_ack_in : STD_LOGIC;
    signal regslice_both_data_V_data_7_V_U_apdone_blk : STD_LOGIC;
    signal data_V_data_7_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal data_V_data_7_V_TVALID_int : STD_LOGIC;
    signal data_V_data_7_V_TREADY_int : STD_LOGIC;
    signal regslice_both_data_V_data_7_V_U_ack_in : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_data_V_data_0_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_0_V_TDATA,
        vld_in => data_V_data_0_V_TVALID,
        ack_in => regslice_both_data_V_data_0_V_U_ack_in,
        data_out => data_V_data_0_V_TDATA_int,
        vld_out => data_V_data_0_V_TVALID_int,
        ack_out => data_V_data_0_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_0_V_U_apdone_blk);

    regslice_both_data_V_data_1_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_1_V_TDATA,
        vld_in => data_V_data_1_V_TVALID,
        ack_in => regslice_both_data_V_data_1_V_U_ack_in,
        data_out => data_V_data_1_V_TDATA_int,
        vld_out => data_V_data_1_V_TVALID_int,
        ack_out => data_V_data_1_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_1_V_U_apdone_blk);

    regslice_both_data_V_data_2_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_2_V_TDATA,
        vld_in => data_V_data_2_V_TVALID,
        ack_in => regslice_both_data_V_data_2_V_U_ack_in,
        data_out => data_V_data_2_V_TDATA_int,
        vld_out => data_V_data_2_V_TVALID_int,
        ack_out => data_V_data_2_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_2_V_U_apdone_blk);

    regslice_both_data_V_data_3_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_3_V_TDATA,
        vld_in => data_V_data_3_V_TVALID,
        ack_in => regslice_both_data_V_data_3_V_U_ack_in,
        data_out => data_V_data_3_V_TDATA_int,
        vld_out => data_V_data_3_V_TVALID_int,
        ack_out => data_V_data_3_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_3_V_U_apdone_blk);

    regslice_both_data_V_data_4_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_4_V_TDATA,
        vld_in => data_V_data_4_V_TVALID,
        ack_in => regslice_both_data_V_data_4_V_U_ack_in,
        data_out => data_V_data_4_V_TDATA_int,
        vld_out => data_V_data_4_V_TVALID_int,
        ack_out => data_V_data_4_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_4_V_U_apdone_blk);

    regslice_both_data_V_data_5_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_5_V_TDATA,
        vld_in => data_V_data_5_V_TVALID,
        ack_in => regslice_both_data_V_data_5_V_U_ack_in,
        data_out => data_V_data_5_V_TDATA_int,
        vld_out => data_V_data_5_V_TVALID_int,
        ack_out => data_V_data_5_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_5_V_U_apdone_blk);

    regslice_both_data_V_data_6_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_6_V_TDATA,
        vld_in => data_V_data_6_V_TVALID,
        ack_in => regslice_both_data_V_data_6_V_U_ack_in,
        data_out => data_V_data_6_V_TDATA_int,
        vld_out => data_V_data_6_V_TVALID_int,
        ack_out => data_V_data_6_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_6_V_U_apdone_blk);

    regslice_both_data_V_data_7_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => data_V_data_7_V_TDATA,
        vld_in => data_V_data_7_V_TVALID,
        ack_in => regslice_both_data_V_data_7_V_U_ack_in,
        data_out => data_V_data_7_V_TDATA_int,
        vld_out => data_V_data_7_V_TVALID_int,
        ack_out => data_V_data_7_V_TREADY_int,
        apdone_blk => regslice_both_data_V_data_7_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_259_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_1))) then 
                i1_0_reg_259 <= ap_const_lv2_0;
            elsif ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1))) then 
                i1_0_reg_259 <= i_reg_391;
            end if; 
        end if;
    end process;

    j3_0_reg_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) then 
                j3_0_reg_270 <= ap_const_lv2_0;
            elsif ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
                j3_0_reg_270 <= j_2_fu_322_p2;
            end if; 
        end if;
    end process;

    j6_0_reg_281_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) then 
                j6_0_reg_281 <= j_1_fu_374_p2;
            elsif ((not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_1))) then 
                j6_0_reg_281 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    j_0_reg_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) then 
                j_0_reg_248 <= j_fu_298_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_0_reg_248 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                i_reg_391 <= i_fu_310_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif ((not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(icmp_ln81_fu_292_p2, io_acc_block_signal_op31)
    begin
                ap_block_state2 <= ((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0));
    end process;


    ap_block_state3_assign_proc : process(icmp_ln86_fu_304_p2, io_acc_block_signal_op43)
    begin
                ap_block_state3 <= ((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0));
    end process;


    ap_block_state4_assign_proc : process(icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
                ap_block_state4 <= (((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)));
    end process;


    ap_block_state5_assign_proc : process(icmp_ln99_fu_368_p2, io_acc_block_signal_op75)
    begin
                ap_block_state5 <= ((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op75)
    begin
        if ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_V_data_0_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_0_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_0_V_TDATA_blk_n <= data_V_data_0_V_TVALID_int;
        else 
            data_V_data_0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_TREADY_assign_proc : process(data_V_data_0_V_TVALID, regslice_both_data_V_data_0_V_U_ack_in)
    begin
        if (((data_V_data_0_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_0_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_0_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_0_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_0_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_0_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_0_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_1_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_1_V_TDATA_blk_n <= data_V_data_1_V_TVALID_int;
        else 
            data_V_data_1_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_TREADY_assign_proc : process(data_V_data_1_V_TVALID, regslice_both_data_V_data_1_V_U_ack_in)
    begin
        if (((data_V_data_1_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_1_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_1_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_1_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_1_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_1_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_2_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_2_V_TDATA_blk_n <= data_V_data_2_V_TVALID_int;
        else 
            data_V_data_2_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_TREADY_assign_proc : process(data_V_data_2_V_TVALID, regslice_both_data_V_data_2_V_U_ack_in)
    begin
        if (((data_V_data_2_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_2_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_2_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_2_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_2_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_2_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_3_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_3_V_TDATA_blk_n <= data_V_data_3_V_TVALID_int;
        else 
            data_V_data_3_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_TREADY_assign_proc : process(data_V_data_3_V_TVALID, regslice_both_data_V_data_3_V_U_ack_in)
    begin
        if (((data_V_data_3_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_3_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_3_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_3_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_3_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_3_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_4_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_4_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_4_V_TDATA_blk_n <= data_V_data_4_V_TVALID_int;
        else 
            data_V_data_4_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_4_V_TREADY_assign_proc : process(data_V_data_4_V_TVALID, regslice_both_data_V_data_4_V_U_ack_in)
    begin
        if (((data_V_data_4_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_4_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_4_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_4_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_4_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_4_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_4_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_5_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_5_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_5_V_TDATA_blk_n <= data_V_data_5_V_TVALID_int;
        else 
            data_V_data_5_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_5_V_TREADY_assign_proc : process(data_V_data_5_V_TVALID, regslice_both_data_V_data_5_V_U_ack_in)
    begin
        if (((data_V_data_5_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_5_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_5_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_5_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_5_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_5_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_5_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_6_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_6_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_6_V_TDATA_blk_n <= data_V_data_6_V_TVALID_int;
        else 
            data_V_data_6_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_6_V_TREADY_assign_proc : process(data_V_data_6_V_TVALID, regslice_both_data_V_data_6_V_U_ack_in)
    begin
        if (((data_V_data_6_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_6_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_6_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_6_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_6_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_6_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_6_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_7_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, data_V_data_7_V_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_7_V_TDATA_blk_n <= data_V_data_7_V_TVALID_int;
        else 
            data_V_data_7_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_7_V_TREADY_assign_proc : process(data_V_data_7_V_TVALID, regslice_both_data_V_data_7_V_U_ack_in)
    begin
        if (((data_V_data_7_V_TVALID = ap_const_logic_1) and (regslice_both_data_V_data_7_V_U_ack_in = ap_const_logic_1))) then 
            data_V_data_7_V_TREADY <= ap_const_logic_1;
        else 
            data_V_data_7_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_7_V_TREADY_int_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            data_V_data_7_V_TREADY_int <= ap_const_logic_1;
        else 
            data_V_data_7_V_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_310_p2 <= std_logic_vector(unsigned(i1_0_reg_259) + unsigned(ap_const_lv2_1));
    icmp_ln81_fu_292_p2 <= "1" when (j_0_reg_248 = ap_const_lv3_5) else "0";
    icmp_ln86_fu_304_p2 <= "1" when (i1_0_reg_259 = ap_const_lv2_3) else "0";
    icmp_ln90_fu_316_p2 <= "1" when (j3_0_reg_270 = ap_const_lv2_3) else "0";
    icmp_ln99_fu_368_p2 <= "1" when (j6_0_reg_281 = ap_const_lv3_5) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op75)
    begin
        if ((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op31 <= (res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op43 <= (res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op54 <= (data_V_data_7_V_TVALID_int and data_V_data_6_V_TVALID_int and data_V_data_5_V_TVALID_int and data_V_data_4_V_TVALID_int and data_V_data_3_V_TVALID_int and data_V_data_2_V_TVALID_int and data_V_data_1_V_TVALID_int and data_V_data_0_V_TVALID_int);
    io_acc_block_signal_op63 <= (res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op66 <= (res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    io_acc_block_signal_op75 <= (res_V_data_7_V_full_n and res_V_data_6_V_full_n and res_V_data_5_V_full_n and res_V_data_4_V_full_n and res_V_data_3_V_full_n and res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    j_1_fu_374_p2 <= std_logic_vector(unsigned(j6_0_reg_281) + unsigned(ap_const_lv3_1));
    j_2_fu_322_p2 <= std_logic_vector(unsigned(j3_0_reg_270) + unsigned(ap_const_lv2_1));
    j_fu_298_p2 <= std_logic_vector(unsigned(j_0_reg_248) + unsigned(ap_const_lv3_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_0_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_0_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_0_V_din <= data_V_data_0_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_0_V_din <= ap_const_lv16_0;
        else 
            res_V_data_0_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_1_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_1_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_1_V_din <= data_V_data_1_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_1_V_din <= ap_const_lv16_0;
        else 
            res_V_data_1_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_2_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_2_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_2_V_din <= data_V_data_2_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_2_V_din <= ap_const_lv16_0;
        else 
            res_V_data_2_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_blk_n_assign_proc : process(res_V_data_3_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_3_V_blk_n <= res_V_data_3_V_full_n;
        else 
            res_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_3_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_3_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_3_V_din <= data_V_data_3_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_3_V_din <= ap_const_lv16_0;
        else 
            res_V_data_3_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_4_V_blk_n_assign_proc : process(res_V_data_4_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_4_V_blk_n <= res_V_data_4_V_full_n;
        else 
            res_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_4_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_4_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_4_V_din <= data_V_data_4_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_4_V_din <= ap_const_lv16_0;
        else 
            res_V_data_4_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_4_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_4_V_write <= ap_const_logic_1;
        else 
            res_V_data_4_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_5_V_blk_n_assign_proc : process(res_V_data_5_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_5_V_blk_n <= res_V_data_5_V_full_n;
        else 
            res_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_5_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_5_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_5_V_din <= data_V_data_5_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_5_V_din <= ap_const_lv16_0;
        else 
            res_V_data_5_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_5_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_5_V_write <= ap_const_logic_1;
        else 
            res_V_data_5_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_6_V_blk_n_assign_proc : process(res_V_data_6_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_6_V_blk_n <= res_V_data_6_V_full_n;
        else 
            res_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_6_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_6_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_6_V_din <= data_V_data_6_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_6_V_din <= ap_const_lv16_0;
        else 
            res_V_data_6_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_6_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_6_V_write <= ap_const_logic_1;
        else 
            res_V_data_6_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_7_V_blk_n_assign_proc : process(res_V_data_7_V_full_n, ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_7_V_blk_n <= res_V_data_7_V_full_n;
        else 
            res_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    res_V_data_7_V_din_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75, data_V_data_7_V_TDATA_int)
    begin
        if ((not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0))) then 
            res_V_data_7_V_din <= data_V_data_7_V_TDATA_int;
        elsif (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)))) then 
            res_V_data_7_V_din <= ap_const_lv16_0;
        else 
            res_V_data_7_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_data_7_V_write_assign_proc : process(ap_CS_fsm_state4, icmp_ln90_fu_316_p2, ap_CS_fsm_state2, icmp_ln81_fu_292_p2, ap_CS_fsm_state3, icmp_ln86_fu_304_p2, ap_CS_fsm_state5, icmp_ln99_fu_368_p2, io_acc_block_signal_op31, io_acc_block_signal_op43, io_acc_block_signal_op54, io_acc_block_signal_op63, io_acc_block_signal_op66, io_acc_block_signal_op75)
    begin
        if (((not(((io_acc_block_signal_op75 = ap_const_logic_0) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln99_fu_368_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op43 = ap_const_logic_0) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln86_fu_304_p2 = ap_const_lv1_0)) or (not(((io_acc_block_signal_op31 = ap_const_logic_0) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln81_fu_292_p2 = ap_const_lv1_0)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or (not((((io_acc_block_signal_op66 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_1)) or ((io_acc_block_signal_op63 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)) or ((io_acc_block_signal_op54 = ap_const_logic_0) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln90_fu_316_p2 = ap_const_lv1_0)))) then 
            res_V_data_7_V_write <= ap_const_logic_1;
        else 
            res_V_data_7_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
